LTO_ENABLE = yes
RGB_MATRIX_ENABLE = yes
AUTO_SHIFT_ENABLE = yes
BOOTMAGIC_ENABLE = yes
EXTRAKEY_ENABLE = yes
MOUSEKEY_ENABLE = yes

TAP_DANCE_ENABLE = no
COMMAND_ENABLE = no
INTROSPECTION_ENABLE = no
